### ISSUE TITLE
Wrong “keyboard” layout with German keyboard (macOS)

### ISSUE THREAD

**Issue by Tekl** [Chordian/sidfactory2#158] opened 2022-07-21 14:32 UTC
**Describe the bug**
When I enter notes, the keys Z and Y are exchanged so, the key left to X (Note D)  does not enter the Note C but an A.

**To Reproduce**
1. Use macOS with German keyboard layout (QWERTZ)
2. Open SIDFactoryII
3. Enter some notes with the Mac keyboard in the track editor

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 12.5 Monterey
 - Version of SIDFactoryII: 2021-12-30.fd30510 (1)

**Additional context**
Interestingly, the Y/Z keys works correct in other situations inside SIDFactory. Cmd+Z and typing Z/Y is possible with the right keys. So, the problem only affects the note input.

**Comment by kebby** [comment] 2022-08-21 17:02
+1 for this (PC with German layout here). It would really help if you also made the note input keys configurable; no need for full intl keyboard layout support I'd say. Everything else works perfectly.

**Comment by micheldebree** [comment] 2022-08-28 05:24
This will probably be resolved by #74

**Comment by micheldebree** [comment] 2022-09-01 11:13
Closed as duplicate of #74

**Closed** 2022-09-01 11:13 UTC
Labels: bug
